	USE UNIVER;
/*Выбрать всех студентов с оценками от 6 до 8 и вывести в порядке убывания*/
SELECT FACULTY.FACULTY,PULPIT.PULPIT,PROFESSION.PROFESSION_NAME,SUBJECT.SUBJECT_NAME,PROGRESS.NOTE,
CASE WHEN (PROGRESS.NOTE=6) THEN 'шесть'
	WHEN (PROGRESS.NOTE=7) THEN 'семь'
	WHEN (PROGRESS.NOTE=8) THEN 'восемь'
	END [PROGRESS.NOTE]
	FROM PROGRESS
INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN SUBJECT ON SUBJECT.SUBJECT = PROGRESS.SUBJECT
INNER JOIN GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
INNER JOIN PULPIT ON PULPIT.PULPIT=SUBJECT.PULPIT
INNER JOIN FACULTY ON FACULTY.FACULTY = PULPIT.FACULTY
WHERE PROGRESS.NOTE BETWEEN 6 AND 8

	/*Переписать задание выше чтобы сначала были 7,потом 8,а потом 6*/
SELECT FACULTY.FACULTY,PULPIT.PULPIT,PROFESSION.PROFESSION_NAME,SUBJECT.SUBJECT_NAME,PROGRESS.NOTE,
CASE WHEN (PROGRESS.NOTE=6) THEN 'шесть'
	WHEN (PROGRESS.NOTE=7) THEN 'семь'
	WHEN (PROGRESS.NOTE=8) THEN 'восемь'
	END [PROGRESS.NOTE]
	FROM PROGRESS
INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
INNER JOIN SUBJECT ON SUBJECT.SUBJECT = PROGRESS.SUBJECT
INNER JOIN GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
INNER JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
INNER JOIN PULPIT ON PULPIT.PULPIT=SUBJECT.PULPIT
INNER JOIN FACULTY ON FACULTY.FACULTY = PULPIT.FACULTY
	WHERE PROGRESS.NOTE BETWEEN 6 AND 8
ORDER BY
(CASE 
	 WHEN (PROGRESS.NOTE='6') THEN 3
	 WHEN (PROGRESS.NOTE='7') THEN 1
	 WHEN (PROGRESS.NOTE='8') THEN 2
	END);


/*Получить полный перечень кафедр и преподавателей на этих кафедрах*/
SELECT PULPIT.PULPIT_NAME[PULPITS],ISNULL (TEACHER.TEACHER_NAME,'***')[TEACHERS]
FROM PULPIT LEFT OUTER JOIN TEACHER 
ON PULPIT.PULPIT=TEACHER.PULPIT

/*Использовать RIGHT OUTER JOIN*/
SELECT ISNULL (TEACHER.TEACHER_NAME,'***')[TEACHERS],PULPIT.PULPIT_NAME[PULPITS]
FROM TEACHER RIGHT OUTER JOIN PULPIT
ON TEACHER.PULPIT=PULPIT.PULPIT

/*FULL OUTER JOIN*/
SELECT PULPIT.FACULTY, PULPIT.PULPIT, PULPIT.PULPIT_NAME
FROM PULPIT FULL outer join TEACHER
ON PULPIT.PULPIT = TEACHER.PULPIT
WHERE TEACHER.TEACHER IS NULL

SELECT PULPIT.FACULTY, PULPIT.PULPIT, PULPIT.PULPIT_NAME
FROM PULPIT FULL outer join TEACHER
ON PULPIT.PULPIT = TEACHER.PULPIT
WHERE TEACHER.TEACHER IS NOT NULL

SELECT *FROM PULPIT FULL outer join TEACHER
ON PULPIT.PULPIT = TEACHER.PULPIT

/*CROSS  JOIN*/
SELECT AUDITORIUM_TYPE.AUDITORIUM_TYPENAME,AUDITORIUM.AUDITORIUM_NAME
FROM AUDITORIUM_TYPE CROSS  JOIN AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_TYPE=AUDITORIUM_TYPE.AUDITORIUM_TYPE


