USE UNIVER;
SELECT PROGRESS.NOTE,STUDENT.NAME,GROUPS.IDGROUP,SUBJECT.SUBJECT_NAME,
PULPIT.PULPIT_NAME,FACULTY.FACULTY_NAME
FROM PROGRESS,STUDENT,GROUPS,SUBJECT,PULPIT,FACULTY
WHERE PROGRESS.NOTE BETWEEN 6 AND 8